Traceback (most recent call last):
  File "/Volumes/vrona_SSD/FHE.Chess/src/new_model_src_new/magic_chess_new.py", line 72, in <module>
    train_valid(model, train_loader, valid_loader, criterion_from, criterion_to)
  File "/Volumes/vrona_SSD/FHE.Chess/src/new_model_src_new/trainvalidtest.py", line 87, in train_valid
    loss_from = criterion_from(output[:,0,:], target[:,0,:])
IndexError: too many indices for tensor of dimension 1
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
torch.Size([64, 1, 8, 8]) torch.Size([64, 8, 8])